version: "3.3"
services:

  backend:
    container_name: backend
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on: 
      - db
    env_file:
      - backend/.env
    container_name: backend
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./backend:/home/src/
    ports:
      - "80:8000"

  db:
    container_name: mariadb
    image: mariadb
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=r00t
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
    volumes: 
      - "sqldatavolume:/var/lib/mysql"
      - "./scripts/sql/schema.sql:/docker-entrypoint-initdb.d/1.sql"
  
volumes:
  sqldatavolume: